"""create follow relationships

Revision ID: 693e873defa2
Revises: ab23f63743bf
Create Date: 2025-10-29 23:59:37.441708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '693e873defa2'
down_revision: Union[str, Sequence[str], None] = 'ab23f63743bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable UUID extension if not already enabled
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_follow_follower_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], name=op.f('fk_follow_following_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow'))
    )
    op.create_index(op.f('ix_follow_follower_id'), 'follow', ['follower_id'], unique=False)
    op.create_index('ix_follow_following_id', 'follow', ['following_id'], unique=False)
    op.create_index('uq_follower_following', 'follow', ['follower_id', 'following_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_follower_following', table_name='follow')
    op.drop_index('ix_follow_following_id', table_name='follow')
    op.drop_index(op.f('ix_follow_follower_id'), table_name='follow')
    op.drop_table('follow')
    # ### end Alembic commands ###
